-- +goose Up
CREATE TABLE message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    BIGINT NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
    text       TEXT NOT NULL CHECK (LENGTH(text) >= 1),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Composite index for query: WHERE chat_id = ? ORDER BY created_at DESC
CREATE INDEX idx_message_chat_created ON message(chat_id, created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS message;

